parameters:
    log_batch_max_size: 1000
    log_batch_size: 1

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Contract\LogIngestionServiceInterface: '@App\Service\Log\LogIngestionService'
