framework:
    messenger:
        transports:
            async:
                dsn: "amqp://%env(APP_RABBITMQ_USER)%:%env(APP_RABBITMQ_PASSWORD)%@%env(APP_RABBITMQ_HOST)%:%env(APP_RABBITMQ_PORT)%/%env(APP_RABBITMQ_VHOST)%"
                options:
                    exchange:
                        name: logs.ingest
                        type: direct
                        default_publish_routing_key: logs.ingest
                    queues:
                        logs.ingest:
                            binding_keys: [logs.ingest]
                            arguments:
                                x-max-priority: 10
        routing:
            App\Message\LogBatchMessage: async
